#!/usr/bin/env python

from tapestry_plugin import Tools
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw

if __name__ == '__main__':
    image = Tools.read_image()
    draw = ImageDraw.Draw(image)
    draw.text((5, 5),"Sample Text",(255,255,255)) 
    Tools.write_image(image)
